### ISSUE TITLE
Issue with the upstream configuration

### ISSUE THREAD

**Issue by inkitm** [bitly/oauth2_proxy#504]
I am using the oauth2_proxy docker container in creating a pod in openshift. I have given the arguments to the start of the docker container as below,

["email-domain=*","upstream=http://localhost:8080/","cookie-secure=false","redirect-url=https://my main app page/oauth2/callback","http-address=0.0.0.0:4180","cookie-domain=localhost:4180"]

While running the container, I am getting the following error,

panic: unknown upstream protocol
```
--
  |  
  | goroutine 1 [running]:
  | panic(0x8118c0, 0xc820122330)
  | /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
  | main.NewOAuthProxy(0xc82011e000, 0xc82011c1e0, 0x1)
  | /Users/jehiah/projects/gopath/src/github.com/bitly/oauth2_proxy/oauthproxy.go:142 +0x256c
  | main.main()
  | /Users/jehiah/projects/gopath/src/github.com/bitly/oauth2_proxy/main.go:103 +0x1830
```
Can you please help?

Thanks in Advance

**Comment by jehiah** [comment]
@inkitm can you provide details on what version you are running, and the full startup logs including traceback? I'm assuming you got this traceback immediately but it would be helpful to confirm that.

**Comment by inkitm** [comment]
I am using mryu/oauth2-proxy:2.1 version and deploying it to openshift 3.4.1.7

Thats the only error trace I have got at my pod.

**Comment by inkitm** [comment]
Or can you please point me to another docker image which may work better.
Thanks

**Comment by jehiah** [comment]
@inkitm can you provide the full logs from your `oauth2_proxy` instance? This sounds like the bug resolved by #431

**Comment by inkitm** [comment]
Thanks after understanding that this may be a bug, i rebuilt my docker image using the latest version and the old issue seems to have been resolved.
Now with new image, I am using the following oauth_proxy parameters,

--email-domain="*" --upstream="http://myappname:8080/" --approval-prompt="auto" --redirect-url="http://my_oauth_pod_hostname:4180/oauth2/callback"  --cookie-secret="somesecret" --cookie-secure=false  --provider=google  --client-id=""  --client-secret="" --http-address="0.0.0.0:4180"

Now, when I click on the oauth_proxy url "http://my_oauth_pod_hostname:4180",
It takes me to the google authentication, authenticates me and then brings me back to the page I began my journey from.
I observe that it is also the same url which I have given in my nginx.conf file as 
rewrite /login http://my_oauth_pod_hostname:4180/oauth2/sign_in redirect

Following is the traceback from oauth_proxy,

2017/11/22 17:17:43 oauthproxy.go:130: mapping path "/" => upstream "http://myapp_hostname:8080"
2017/11/22 17:17:43 oauthproxy.go:157: OAuthProxy configured for Google Client ID: "my client id"
2017/11/22 17:17:43 oauthproxy.go:163: Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domain: refresh:disabled
2017/11/22 17:17:43 http.go:49: HTTP: listening on 0.0.0.0:4180
10.130.2.1 - - [22/Nov/2017:17:34:34 +0000] my_oauth_hostname:4180 GET - "/oauth2/start?rd=%2Foauth2%2Fsign_in%3Fnext%3D%252F" HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 302 414 0.000
10.130.2.1 - - [22/Nov/2017:17:34:35 +0000] my_oauth_hostname:4180 GET - "/oauth2/callback?state=58e3d31c1d37887f05547c818d4d5a65:/oauth2/sign_in?next%3D%252F&code=4/lZ11tw_jU2H1jN-WvqMjPPRMuKYeJ454y8iNiIaug14" HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 302 47 0.306
2017/11/22 17:34:35 oauthproxy.go:556: 10.130.2.1:37904 authentication complete Session{mygmail@gmail.com token:true expires:2017-11-22 18:34:35 +0000 UTC}
10.130.2.1 - - [22/Nov/2017:17:34:35 +0000] my_oauth_hostname:4180 GET - "/oauth2/sign_in?next=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 200 2497 0.000
2017/11/22 17:34:35 oauthproxy.go:601: 10.130.2.1:37904 Cookie "_oauth2_proxy" not present
10.130.2.1 - - [22/Nov/2017:17:34:35 +0000] my_oauth_hostname:4180 GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 403 2485 0.000
10.130.2.1 - - [22/Nov/2017:17:34:40 +0000] my_oauth_hostname:4180 GET - "/oauth2/start?rd=%2Foauth2%2Fsign_in%3Fnext%3D%252F" HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 302 414 0.000
2017/11/22 17:34:40 oauthproxy.go:556: 10.130.2.1:38188 authentication complete Session{mygmail@gmail.com token:true expires:2017-11-22 18:34:40 +0000 UTC}
10.130.2.1 - - [22/Nov/2017:17:34:40 +0000] my_oauth_hostname:4180 GET - "/oauth2/callback?state=539c001ecded0724248b7b2d268efec0:/oauth2/sign_in?next%3D%252F&code=4/bFtuYexH9oRXLSHFb8K16yR3nVFt_bseJPPIlS1zrKE" HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 302 47 0.171
10.130.2.1 - - [22/Nov/2017:17:34:41 +0000] my_oauth_hostname:4180 GET - "/oauth2/sign_in?next=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 200 2497 0.000
2017/11/22 17:34:41 oauthproxy.go:601: 10.130.2.1:38188 Cookie "_oauth2_proxy" not present
10.130.2.1 - - [22/Nov/2017:17:34:41 +0000] my_oauth_hostname:4180 GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 403 2485 0.000

Please Help.

**Comment by inkitm** [comment]
Looking at #157, I have also tried adding --cookie-domain="my_oauth_pod_hostname:4180" in my oauth config now but still the same result. It is still redirecting me to my original URL "my_oauth_pod_hostname:4180/oauth2/sign_in?next=%2F#" and now my upstream URL.

Please Help.

**Comment by ploxiln** [comment]
Your mention of "openshift pod" makes me think of kubernetes ... this could be similar to #456 

The logs and settings you post are hard to read, please learn to use triple-backticks quoting, like so:

    ```
    multiple lines to be quoted
    inside triple backticks
    triple backticks on their own line with nothing else
    ```

**Comment by jehiah** [comment]
`GET - "/oauth2/start?rd=%2Foauth2%2Fsign_in%3Fnext%3D%252F"`  is a symptom of #456 so closing this. If you visit a URL like `/` you should be able to authenticate fine.

you did auth successfully `authentication complete Session{mygmail@gmail.com token:true expires:2017-11-22 18:34:35 +0000 UTC}` so you should be ok otherwise.

**Comment by Puneeth-n** [comment]
@jehiah what do you mean by `If you visit a URL like / you should be able to authenticate fine.` ? Can you please elaborate?
